name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest

    - name: Build Docker image
      run: |
        docker build -t my-web-app .

    - name: Save artifact
      run: |
        mkdir -p output
        echo "dummy file content" > output/my-web-app.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-web-app
        path: output/my-web-app.zip

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: v1.0.1 # Incrementar versão
        release_name: Release v1.0.1
        body: "Release of my web app"
        draft: false
        prerelease: false

    - name: Set environment variable for upload URL
      run: echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: output/my-web-app.zip
        asset_name: my-web-app.zip
        asset_content_type: application/zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to environment
      run: |
        echo "Deploying application to test environment"
        # Comandos de deploy podem ser adicionados aqui
        # Exemplo: ssh, kubectl, aws cli etc.

    - name: Notify on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: GitHub Actions CI/CD Pipeline Failure
        to: ${{ secrets.DEVELOPER_EMAIL }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: "A etapa do pipeline falhou."
